# Funding channels for Vulnera
# Sponsorships go directly to Vulnera Industries and are used as general company revenue to improve the product.
# There are no perks or entitlements associated with sponsorship yet.

github: [k5602]
